apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-training
spec:
  selector:
    matchLabels:
      app: devops-training
  template:
    metadata:
      labels:
        app: devops-training
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: springapp
        image: 34.71.229.107:8083/springapp:37
        command: ["/bin/sh"]
        args: ["-c","sh /usr/local/tomcat/bin/startup.sh;while true; do echo hello; sleep 10;done"]
        imagePullPolicy: IfNotPresent
        ports:
            - name: http
              containerPort: 8080
  replicas: 2
---
apiVersion: v1
kind: Service
metadata:
  name: devops-training-app-service
  labels:
    app: devops-training
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31884
    protocol: TCP
    name: http
  selector:
    app: devops-training
